spring:
  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3312/rest
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: spring-boot_security-demo
  liquibase:
    change-log: 'classpath:/db/migrations/changeLog.xml'


server:
  port: 8099